In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from torch import nn

In [3]:
torch.__version__

'2.5.1'

In [7]:
torch.mps.is_available()

True

# Creating data using Linear Regression

#### Linear Regression equation: Y = a + bx

In [8]:
#creating known parameters
weight = 0.7 #b
bias = 0.3 #a

In [9]:
#Creating data
start = 0
end = 1

step = 0.02
X = torch.arange(start, end, step)

In [12]:
X, X.size()

(tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
         0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
         0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
         0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
         0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
         0.9000, 0.9200, 0.9400, 0.9600, 0.9800]),
 torch.Size([50]))

In [13]:
X = X.unsqueeze(dim = 1)

In [15]:
X.size()

torch.Size([50, 1])

In [17]:
Y = bias + weight * X

In [18]:
X[:10]

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800],
        [0.1000],
        [0.1200],
        [0.1400],
        [0.1600],
        [0.1800]])

In [19]:
Y[:10]

tensor([[0.3000],
        [0.3140],
        [0.3280],
        [0.3420],
        [0.3560],
        [0.3700],
        [0.3840],
        [0.3980],
        [0.4120],
        [0.4260]])

In [21]:
len(X), len(Y)

(50, 50)