In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.item() #get tensor back as int

7

In [5]:
vector = torch.tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim #ndim = number of dimensions

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], [9, 8]])

In [10]:
matrix

tensor([[7, 8],
        [9, 8]])

In [11]:
matrix.ndim

2

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [3, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [16]:
#Random Tensors, neural networks start with random tensors
random_tensor = torch.rand(3, 4, 3)

In [17]:
random_tensor

tensor([[[0.4556, 0.7565, 0.0022],
         [0.5181, 0.9566, 0.6343],
         [0.4262, 0.1557, 0.8165],
         [0.2809, 0.0268, 0.6019]],

        [[0.4137, 0.6275, 0.3019],
         [0.2799, 0.7664, 0.4984],
         [0.5429, 0.2048, 0.5253],
         [0.2707, 0.6468, 0.6953]],

        [[0.6262, 0.8292, 0.8091],
         [0.4024, 0.2363, 0.3501],
         [0.3983, 0.2953, 0.7151],
         [0.5895, 0.1152, 0.4479]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([3, 4, 3])

In [20]:
#similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))#color channels can also come at the start, 3, 224, 224
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#tensors with zeros and ones
zeros = torch.zeros(3, 4)

In [22]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
#default datatype is torch.float
ones.dtype

torch.float32

In [25]:
#creating a range of tensors and tensors-like
#We use torch.arange, torch.range will be deprecated soon
zero_to_nine = torch.arange(0,10)

In [26]:
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
step = torch.arange(start= 1, end = 1000, step = 99)

In [28]:
step

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [29]:
#creating tensors like
#used when shape is not to be specified, and shape of some other tensor to be use
ten_zeros = torch.zeros_like(zero_to_nine)

In [30]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)

In [32]:
float_32_tensor

tensor([3., 6., 9.])

In [33]:
#default datatype is float32, even when dtype is specified as None)
float_32_tensor.dtype

torch.float32

In [34]:
#say float 16, tensor has 3 parameters
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, #what dtype is the tensor
                               device = None, #What device is the tensor on
                               requires_grad = False) #whether or not to track gradients witht this tensors operation
float_16_tensor.dtype

torch.float16

In [35]:
#to change dtype
float_16_tensor_of_32 = float_16_tensor.type(torch.float16)
float_16_tensor_of_32

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor#works here but may result in errors when training large neural networks

tensor([ 9., 36., 81.])

In [37]:
long_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)

### Getting infos from tensors

In [39]:
tensor = torch.rand(3,4)

In [40]:
tensor.shape

torch.Size([3, 4])

In [42]:
tensor.dtype

torch.float32

In [45]:
tensor.device #cpu is default

device(type='cpu')

In [44]:
tensor.size()

torch.Size([3, 4])

### Tensor Operations

Addition, Subtraction, Multiplication, Division, Matrix Multiplication

In [60]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [61]:
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [62]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [63]:
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [65]:
#inbuilt tensor arithmetic function
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [66]:
torch.add(tensor, 11)

tensor([12., 13., 14.])

In [67]:
torch.sub(tensor, 1)

tensor([0., 1., 2.])

### Matrix Multiplication

Two ways to perform multiplication:

* element wise multiplication
* matrix multiplication

In [69]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [70]:
#element wise
tensor * tensor

tensor([1., 4., 9.])

In [71]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14.)

In [75]:
#manually using a for loop (not recommended
import time
start_time = time.time()

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

end_time = time.time()

print("Sum of squares:", value)
print("Execution time:", end_time - start_time, "seconds")

Sum of squares: tensor(14.)
Execution time: 0.0010771751403808594 seconds


In [77]:
start_time = time.time()

print(torch.matmul(tensor, tensor), '\n')
end_time = time.time()

end_time - start_time

tensor(14.) 



0.0048580169677734375

Rules for matrix multiplication

* Inner dimensions must match, meaning a * b and b * c will work but, a * b and c * d wont work
* Resulting matrix has shape of the outer dimensions

In [79]:
torch.matmul(torch.rand(3, 7) , torch.rand(7, 10))

tensor([[1.0334, 2.2868, 1.8950, 1.8190, 2.0291, 1.9955, 2.4320, 1.6528, 2.1708,
         1.7255],
        [1.5049, 2.5625, 2.5567, 2.3215, 2.0500, 2.5848, 2.8849, 2.4314, 2.6151,
         1.8914],
        [1.5613, 2.2630, 2.4254, 2.1879, 2.1272, 2.5171, 2.8264, 1.9788, 2.0347,
         1.9010]])

Dealing with shape errors

In [95]:
tensor_A = torch.tensor([[1, 2], [3, 4], [4, 5]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
#torch.mm is the same as torch.matmul
# torch.mm(tensor_A, tensor_B), shape error

In [92]:
tensor_A.shape

torch.Size([3, 2])

In [93]:
tensor_B.shape

torch.Size([3, 2])

In [94]:
tensor_B.T.shape

torch.Size([2, 3])

In [96]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [98]:
torch.mm(tensor_A, tensor_B.T) #works

tensor([[27, 30, 33],
        [61, 68, 75],
        [78, 87, 96]])

In [99]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Tensor aggregation

In [100]:
x = torch.arange(0, 100, 10) 

In [101]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [103]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [104]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [110]:
#torch.mean(x) #not the right datatype error
#because
x.dtype #int 64 which is long

torch.int64

In [111]:
torch.mean(x.type(torch.float32)) 

tensor(45.)

In [112]:
x.type(torch.float32).mean()

tensor(45.)

torch.mean() funtion requires a tensor of float32 dtype to work

In [113]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Positions of min and max

In [114]:
torch.argmax(x)

tensor(9)

In [115]:
torch.argmin(x)

tensor(0)

In [116]:
x.argmax()

tensor(9)

In [117]:
x.argmin()

tensor(0)