In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.item() #get tensor back as int

7

In [5]:
vector = torch.tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim #ndim = number of dimensions

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], [9, 8]])

In [10]:
matrix

tensor([[7, 8],
        [9, 8]])

In [11]:
matrix.ndim

2

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [3, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [16]:
#Random Tensors, neural networks start with random tensors
random_tensor = torch.rand(3, 4, 3)

In [17]:
random_tensor

tensor([[[0.7088, 0.7955, 0.6303],
         [0.8336, 0.9507, 0.1836],
         [0.5990, 0.0382, 0.0126],
         [0.2281, 0.7776, 0.2725]],

        [[0.1566, 0.9615, 0.2055],
         [0.5576, 0.8123, 0.8966],
         [0.4494, 0.0288, 0.5757],
         [0.2971, 0.4576, 0.3182]],

        [[0.3390, 0.1233, 0.8966],
         [0.6837, 0.8524, 0.2318],
         [0.5516, 0.9991, 0.1836],
         [0.5629, 0.3686, 0.9486]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([3, 4, 3])

In [20]:
#similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))#color channels can also come at the start, 3, 224, 224
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#tensors with zeros and ones
zeros = torch.zeros(3, 4)

In [22]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
#default datatype is torch.float
ones.dtype

torch.float32

In [25]:
#creating a range of tensors and tensors-like
#We use torch.arange, torch.range will be deprecated soon
zero_to_nine = torch.arange(0,10)

In [26]:
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
step = torch.arange(start= 1, end = 1000, step = 99)

In [28]:
step

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [29]:
#creating tensors like
#used when shape is not to be specified, and shape of some other tensor to be use
ten_zeros = torch.zeros_like(zero_to_nine)

In [30]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)

In [32]:
float_32_tensor

tensor([3., 6., 9.])

In [33]:
#default datatype is float32, even when dtype is specified as None)
float_32_tensor.dtype

torch.float32

In [34]:
#say float 16, tensor has 3 parameters
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, #what dtype is the tensor
                               device = None, #What device is the tensor on
                               requires_grad = False) #whether or not to track gradients witht this tensors operation
float_16_tensor.dtype

torch.float16

In [35]:
#to change dtype
float_16_tensor_of_32 = float_16_tensor.type(torch.float16)
float_16_tensor_of_32

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor#works here but may result in errors when training large neural networks

tensor([ 9., 36., 81.])

In [37]:
long_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)

### Getting infos from tensors

In [38]:
tensor = torch.rand(3,4)

In [39]:
tensor.shape

torch.Size([3, 4])

In [40]:
tensor.dtype

torch.float32

In [41]:
tensor.device #cpu is default

device(type='cpu')

In [42]:
tensor.size()

torch.Size([3, 4])

### Tensor Operations

Addition, Subtraction, Multiplication, Division, Matrix Multiplication

In [43]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [44]:
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [45]:
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [46]:
tensor = tensor / 10
tensor

tensor([1., 2., 3.])

In [47]:
#inbuilt tensor arithmetic function
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [48]:
torch.add(tensor, 11)

tensor([12., 13., 14.])

In [49]:
torch.sub(tensor, 1)

tensor([0., 1., 2.])

### Matrix Multiplication

Two ways to perform multiplication:

* element wise multiplication
* matrix multiplication

In [50]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [51]:
#element wise
tensor * tensor

tensor([1., 4., 9.])

In [52]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14.)

In [53]:
#manually using a for loop (not recommended
import time
start_time = time.time()

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

end_time = time.time()

print("Sum of squares:", value)
print("Execution time:", end_time - start_time, "seconds")

Sum of squares: tensor(14.)
Execution time: 0.000993967056274414 seconds


In [54]:
start_time = time.time()

print(torch.matmul(tensor, tensor), '\n')
end_time = time.time()

end_time - start_time

tensor(14.) 



0.0005679130554199219

Rules for matrix multiplication

* Inner dimensions must match, meaning a * b and b * c will work but, a * b and c * d wont work
* Resulting matrix has shape of the outer dimensions

In [55]:
torch.matmul(torch.rand(3, 7) , torch.rand(7, 10))

tensor([[2.3173, 2.5536, 1.5443, 1.6251, 2.6937, 1.8648, 1.8332, 2.7440, 1.5512,
         1.7296],
        [2.8157, 2.2748, 2.0355, 1.0509, 2.5871, 1.8079, 1.9256, 2.6608, 2.0272,
         2.4350],
        [1.6757, 1.8097, 1.2745, 1.2800, 1.8436, 1.8838, 1.1084, 1.8943, 1.2345,
         1.6992]])

Dealing with shape errors

In [56]:
tensor_A = torch.tensor([[1, 2], [3, 4], [4, 5]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
#torch.mm is the same as torch.matmul
# torch.mm(tensor_A, tensor_B), shape error

In [57]:
tensor_A.shape

torch.Size([3, 2])

In [58]:
tensor_B.shape

torch.Size([3, 2])

In [59]:
tensor_B.T.shape

torch.Size([2, 3])

In [60]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [61]:
torch.mm(tensor_A, tensor_B.T) #works

tensor([[27, 30, 33],
        [61, 68, 75],
        [78, 87, 96]])

In [62]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Tensor aggregation

In [63]:
x = torch.arange(0, 100, 10) 

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [66]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [67]:
#torch.mean(x) #not the right datatype error
#because
x.dtype #int 64 which is long

torch.int64

In [68]:
torch.mean(x.type(torch.float32)) 

tensor(45.)

In [69]:
x.type(torch.float32).mean()

tensor(45.)

torch.mean() funtion requires a tensor of float32 dtype to work

In [70]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Positions of min and max

In [71]:
torch.argmax(x)

tensor(9)

In [72]:
torch.argmin(x)

tensor(0)

In [73]:
x.argmax()

tensor(9)

In [74]:
x.argmin()

tensor(0)

### Reshaping, stacking, squeezing, unsqueexing

* Reshaping - reshapes input tensort to a defined shape
* View - Return a view of the input of a certain shape but keep the memory of the original tensor
* Stacking - combine multiple tensors on top of each other, vstack- vertical stack, hstack, horizontal stack
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - adda a `1` dimension to a target tensor
* Permut - Return a view of the input with the dimensions permuted in a certain way

In [79]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [81]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [82]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))