In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.item() #get tensor back as int

7

In [5]:
vector = torch.tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim #ndim = number of dimensions

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], [9, 8]])

In [10]:
matrix

tensor([[7, 8],
        [9, 8]])

In [11]:
matrix.ndim

2

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [3, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [16]:
#Random Tensors, neural networks start with random tensors
random_tensor = torch.rand(3, 4, 3)

In [17]:
random_tensor

tensor([[[0.4556, 0.7565, 0.0022],
         [0.5181, 0.9566, 0.6343],
         [0.4262, 0.1557, 0.8165],
         [0.2809, 0.0268, 0.6019]],

        [[0.4137, 0.6275, 0.3019],
         [0.2799, 0.7664, 0.4984],
         [0.5429, 0.2048, 0.5253],
         [0.2707, 0.6468, 0.6953]],

        [[0.6262, 0.8292, 0.8091],
         [0.4024, 0.2363, 0.3501],
         [0.3983, 0.2953, 0.7151],
         [0.5895, 0.1152, 0.4479]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([3, 4, 3])

In [20]:
#similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))#color channels can also come at the start, 3, 224, 224
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#tensors with zeros and ones
zeros = torch.zeros(3, 4)

In [22]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
#default datatype is torch.float
ones.dtype

torch.float32

In [25]:
#creating a range of tensors and tensors-like
#We use torch.arange, torch.range will be deprecated soon
zero_to_nine = torch.arange(0,10)

In [26]:
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
step = torch.arange(start= 1, end = 1000, step = 99)

In [28]:
step

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [29]:
#creating tensors like
#used when shape is not to be specified, and shape of some other tensor to be use
ten_zeros = torch.zeros_like(zero_to_nine)

In [30]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)

In [32]:
float_32_tensor

tensor([3., 6., 9.])

In [33]:
#default datatype is float32, even when dtype is specified as None)
float_32_tensor.dtype

torch.float32

In [34]:
#say float 16, tensor has 3 parameters
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, #what dtype is the tensor
                               device = None, #What device is the tensor on
                               requires_grad = False) #whether or not to track gradients witht this tensors operation
float_16_tensor.dtype

torch.float16

In [35]:
#to change dtype
float_16_tensor_of_32 = float_16_tensor.type(torch.float16)
float_16_tensor_of_32

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor#works here but may result in errors when training large neural networks

tensor([ 9., 36., 81.])

In [37]:
long_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)

Getting infos from tensors

In [39]:
tensor = torch.rand(3,4)

In [40]:
tensor.shape

torch.Size([3, 4])

In [42]:
tensor.dtype

torch.float32

In [43]:
tensor.device

device(type='cpu')

In [44]:
tensor.size()

torch.Size([3, 4])