In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.item() #get tensor back as int

7

In [5]:
vector = torch.tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim #ndim = number of dimensions

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], [9, 8]])

In [10]:
matrix

tensor([[7, 8],
        [9, 8]])

In [11]:
matrix.ndim

2

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [3, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [24]:
#Random Tensors, neural networks start with random tensors
random_tensor = torch.rand(3, 4, 3)

In [25]:
random_tensor

tensor([[[0.1044, 0.4510, 0.0768],
         [0.7619, 0.7740, 0.0318],
         [0.9799, 0.1300, 0.2736],
         [0.3777, 0.6345, 0.2300]],

        [[0.2899, 0.4584, 0.9897],
         [0.2356, 0.9619, 0.0674],
         [0.6189, 0.8886, 0.4979],
         [0.9501, 0.5918, 0.8377]],

        [[0.4251, 0.7345, 0.8247],
         [0.6250, 0.4999, 0.7103],
         [0.1572, 0.8660, 0.8820],
         [0.5314, 0.4778, 0.2028]]])

In [26]:
random_tensor.ndim

3

In [27]:
random_tensor.shape

torch.Size([3, 4, 3])

In [28]:
#similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3))#color channels can also come at the start, 3, 224, 224
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
#tensors with zeros and ones
zeros = torch.zeros(3, 4)

In [31]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
#default datatype is torch.float
ones.dtype

torch.float32

In [38]:
#creating a range of tensors and tensors-like
#We use torch.arange, torch.range will be deprecated soon
zero_to_nine = torch.arange(0,10)

In [39]:
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
step = torch.arange(start= 1, end = 1000, step = 99)

In [41]:
step

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [42]:
#creating tensors like
#used when shape is not to be specified, and shape of some other tensor to be use
ten_zeros = torch.zeros_like(zero_to_nine)

In [43]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [44]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)

In [45]:
float_32_tensor

tensor([3., 6., 9.])

In [46]:
#default datatype is float32, even when dtype is specified as None)
float_32_tensor.dtype

torch.float32

In [49]:
#say float 16, tensor has 3 parameters
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16, #what dtype is the tensor
                               device = None, #What device is the tensor on
                               requires_grad = False) #whether or not to track gradients witht this tensors operation
float_16_tensor.dtype

torch.float16

In [50]:
#to change dtype
float_16_tensor_of_32 = float_16_tensor.type(torch.float16)
float_16_tensor_of_32

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
float_16_tensor * float_32_tensor#works here but may result in errors when training large neural networks

tensor([ 9., 36., 81.])

In [61]:
long_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long)